version: '3.3'
services:
    rediservice:
        build: .
        restart: always
        container_name: ${CONTAINER_NAME}
        logging:
          driver: "json-file"
          options:
            max-size: "10m"
            max-file: "3"
        ports:
            - ${CONTAINER_PORT}:6379
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD} --dir /data --loadmodule /usr/lib/redis/modules/rejson.so
        sysctls:
            - net.core.somaxconn=65536
        volumes: 
            - ./data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        networks:
          - dockernet
networks:
  dockernet:
    external:
      name: dockernet