version: '3.1'
services:
    tricore_db:
        build: .
        restart: always
        container_name : ${CONTAINER_NAME}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - ${CONTAINER_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}