version: '3'
services:
    tricore_db:
        build: .
        restart: always
        container_name : ${CONTAINER_NAME}
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        volumes:
            - ./config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - ${CONTAINER_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
